# Project: Project2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o first.o second.o
LINKOBJ  = main.o first.o second.o
LIBS     = -L"D:/CalabiYau/devc++/Dev-Cpp/MinGW64/lib" -L"D:/CalabiYau/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/CalabiYau/devc++/Dev-Cpp/MinGW64/include" -I"D:/CalabiYau/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/CalabiYau/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/CalabiYau/devc++/Dev-Cpp/MinGW64/include" -I"D:/CalabiYau/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/CalabiYau/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/CalabiYau/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

first.o: first.c
	$(CC) -c first.c -o first.o $(CFLAGS)

second.o: second.c
	$(CC) -c second.c -o second.o $(CFLAGS)
